spring:
  datasource:
    username: service
    password: service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
airpower:
  mqtt:
    user: root
    pass: 123456
app:
  loginUrl: "https://service.hamm.cn/login"