spring:
  profiles:
    active: production
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
  web:
    resources:
      add-mappings: false
  mvc:
    view:
      suffix: .html
      prefix: /
airpower:
  mqtt:
app:
  influxdb:
    url: http://127.0.0.1:8086
    token: airpower
    org: airpower
    bucket: airpower


