spring:
  datasource:
    password: asdfew12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
airpower:
  mqtt:
    host: md4.cn
    user: root
    pass: 123456
app:
  loginUrl: "http://localhost:3000/login"